### ISSUE TITLE
CurtainSyncViewer doesn't pass along options to OpenSeadragon

### ISSUE THREAD

**Issue by locomo** [cuberis/openseadragon-curtain-sync#1]
I'd like to be able to pass some options into the OpenSeadragon viewer when it gets instantiated by CurtainSyncViewer

currently the call to OpenSeagdragon is hardcoded and ignores any options I try to pass 
`this.viewer = OpenSeadragon({
      element: args.container,
      showNavigationControl: false
    });`

would it be possible to pass in an additional options and have them passed along to OpenSeadragon

**Comment by rpovelones** [comment]
Hi Morgan,

You are correct in that currently it is not possible to pass additional options to OpenSeadragon through the CurtainSyncViewer. Currently, there are no plans to add this functionality, however, we are considering the possibility. Alternatively, if you would like to contribute, please feel free to open a PR and I'll take a look at merging it in!

**Comment by iangilman** [comment]
Does seem like a useful feature! Also, the README actually says you can do it already (though it's not true). 

One thing to think about is whether we should pass everything through to OpenSeadragon, or whether we should have a specific OSD options argument so we keep things separate. In other words (using the OSD option `minZoomLevel` as an example), should it be: 

```
var viewer = new CurtainSyncViewer({
  container: document.querySelector('#viewer'),
  minZoomLevel: 0.1
});
```

...Or:

```
var viewer = new CurtainSyncViewer({
  container: document.querySelector('#viewer'),
  osdOptions: {
    minZoomLevel: 0.1
  }
});
```

I think my preference would be for the latter; that way there's no chance of an unintended collision, and it's more clear to anyone reading the code what level the options are intended for. Also, this is more of a power user feature, so it's ok if it's a little more verbose.

Either way, when implementing, keep in mind that the CurtainSyncViewer actually creates and destroys a number of OpenSeadragon viewers while it's running (as the user switches modes), so you'll need to keep the OSD options around and make sure to pass them in to each viewer as they get created.

**Comment by locomo** [comment]
passing in the separate OSD options object makes sense to me! Are there any options you can think of that could break the curtain viewer? I.e. should we check and remove any options that are known to cause problems (i.e. you already hardcode disabling showNavigationControl) .. or like you said it could just be a power user feature and people could be warned that it could cause problems....

**Comment by iangilman** [comment]
I can't think of any options that would cause problems, though there may be some. Let's leave it open for now and we can add a filter for any that come up later.

Thank you for taking a whack at this!

**Comment by locomo** [comment]
btw, do you happen to know of a better way to disable the OSD viewer clickhandler? can it be done via an option?

the only way I could figure out how to do it was like this, but it seems like kind of a hack:
`viewer.innerTracker.clickHandler = null;`

**Comment by iangilman** [comment]
I suppose it depends on what aspect you want disabled. If you just want it to not zoom, you can set the `zoomPerClick`. You can also call `viewer.setMouseNavEnabled(false)`.

**Comment by locomo** [comment]
many thanks .. i think zoomPerClick would disable zooming entirely so i'll try the other one!

**Comment by iangilman** [comment]
I think zoomPerClick just affects clicks, not mouse wheel or touch pinching. I could be wrong, though...
