### ISSUE TITLE
showFullPage control

### ISSUE THREAD

**Issue by TeaBetOrbiter** [cuberis/openseadragon-curtain-sync#3]
Hi there,

I have been trying to implement this recently on our website and the osdOptions command does not seem to permit all default configuration options from openseadragon to be passed in. In particular, I would like to be able to make the deep zoom image go full screen (currently embedded with defined size) but getting these full screen buttons, similar to what is in standard openseadragon, does not seem possible with the above command. Is there a way to do this that I might not see? Thank you for your help!

**Comment by zahranoorcs** [comment]
Hi,
https://github.com/cuberis/openseadragon-curtain-sync/issues/1 
You might find some help here. 
Best,
Zahra

**Comment by TeaBetOrbiter** [comment]
Many thanks. I had a look through this and was able to figure it out!
